/*
 *CS350
 *Dave Nearing
 *Form for collecting survey data.
 */

package csampler;

/**
 *
 * @author danearing
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import csampler.CSample;
import java.awt.List;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Enumeration;
import java.util.HashMap;
import javax.swing.AbstractButton;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.JDialog;
import javax.swing.JList;
import static javax.swing.JOptionPane.showInputDialog;
import javax.swing.ListModel;

/**
 *
 * @author danearing
 */
public class CSampler extends javax.swing.JFrame {
    private HashMap<Integer, CSample> surveyObjectsBuffer;

    /**
     * Creates new form CSample
     */
    public CSampler() {
        surveyList = new DefaultListModel();
        surveyObjects = new HashMap<>();
        initComponents();
        keyGen = new idGenerator();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
                          
    private void initComponents() {

        AddASurvey = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        isFed = new javax.swing.JRadioButton();
        isState = new javax.swing.JRadioButton();
        isPrivate = new javax.swing.JRadioButton();
        isSelf = new javax.swing.JRadioButton();
        isUnemployed = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        affectYes = new javax.swing.JRadioButton();
        affectNo = new javax.swing.JRadioButton();
        affectUnknown = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        submitAddASurvey = new javax.swing.JButton();
        cancelAddASurvey = new javax.swing.JButton();
        zipCode = new javax.swing.JTextField();
        blameR = new javax.swing.JCheckBox();
        blameD = new javax.swing.JCheckBox();
        blameO = new javax.swing.JCheckBox();
        blameC = new javax.swing.JCheckBox();
        participantNo = new javax.swing.JTextField();
        employmentType = new javax.swing.ButtonGroup();
        affectType = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addASurvey = new javax.swing.JButton();
        modifyASurvey = new javax.swing.JButton();
        removeASurvey = new javax.swing.JButton();
        removeAllSurveys = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        surveyListOut = new javax.swing.JList();

        AddASurvey.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        AddASurvey.setTitle("Add A Survey");
        AddASurvey.setMinimumSize(new java.awt.Dimension(552, 250));
        AddASurvey.setPreferredSize(new java.awt.Dimension(552, 250));

        jLabel6.setText("Participant No.");

        jLabel7.setText("Zip Code");

        jLabel8.setText("Employment Type");

        employmentType.add(isFed);
        isFed.setText("Federal");

        employmentType.add(isState);
        isState.setText("State/Local");

        employmentType.add(isPrivate);
        isPrivate.setText("Private");

        employmentType.add(isSelf);
        isSelf.setText("Self-Employed");

        employmentType.add(isUnemployed);
        isUnemployed.setText("Unemployed");

        jLabel9.setText("Does the government shutown affect you?");

        affectType.add(affectYes);
        affectYes.setText("Yes");

        affectType.add(affectNo);
        affectNo.setText("No");

        affectType.add(affectUnknown);
        affectUnknown.setText("Unknown");

        jLabel10.setText("Who/what is to blame for the government shutdown?");

        submitAddASurvey.setText("Submit");
        submitAddASurvey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAddASurveyActionPerformed(evt);
            }
        });

        cancelAddASurvey.setText("Cancel");
        cancelAddASurvey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddASurveyActionPerformed(evt);
            }
        });

        blameR.setText("Republicans(R)");

        blameD.setText("Democrats(D)");

        blameO.setText("Obamacare(O)");

        blameC.setText("The Debt Ceiling(C)");

        participantNo.setEditable(false);

        javax.swing.GroupLayout AddASurveyLayout = new javax.swing.GroupLayout(AddASurvey.getContentPane());
        AddASurvey.getContentPane().setLayout(AddASurveyLayout);
        AddASurveyLayout.setHorizontalGroup(
            AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddASurveyLayout.createSequentialGroup()
                .addGroup(AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddASurveyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddASurveyLayout.createSequentialGroup()
                                .addComponent(isFed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isState)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isPrivate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isSelf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isUnemployed))
                            .addGroup(AddASurveyLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(participantNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddASurveyLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(zipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(AddASurveyLayout.createSequentialGroup()
                                .addComponent(affectYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(affectNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(affectUnknown))
                            .addComponent(jLabel10)))
                    .addGroup(AddASurveyLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(submitAddASurvey)
                        .addGap(133, 133, 133)
                        .addComponent(cancelAddASurvey))
                    .addGroup(AddASurveyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(blameR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blameD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blameO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blameC)))
                .addContainerGap())
        );
        AddASurveyLayout.setVerticalGroup(
            AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddASurveyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(participantNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(zipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isFed)
                    .addComponent(isState)
                    .addComponent(isPrivate)
                    .addComponent(isSelf)
                    .addComponent(isUnemployed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(affectYes)
                    .addComponent(affectNo)
                    .addComponent(affectUnknown))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blameR)
                    .addComponent(blameD)
                    .addComponent(blameO)
                    .addComponent(blameC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitAddASurvey)
                    .addComponent(cancelAddASurvey)))
        );

        AddASurvey.getAccessibleContext().setAccessibleParent(null);
        pack();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Survey On The Government Shutdown");

        jLabel1.setText("Participant No.");

        jLabel2.setText("Zip Code");

        jLabel3.setText("Employment");

        jLabel4.setText("Impact");

        jLabel5.setText("Cause");

        addASurvey.setText("Add");
        addASurvey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSampleAddASurveyClicked(evt);
            }
        });

        modifyASurvey.setText("Modify");
        modifyASurvey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyASurveyActionPerformed(evt);
            }
        });

        removeASurvey.setText("Remove");
        removeASurvey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeASurveyActionPerformed(evt);
            }
        });

        removeAllSurveys.setText("Remove All");
        removeAllSurveys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAllSurveysActionPerformed(evt);
            }
        });

        surveyListOut.setModel(surveyList);
        surveyListOut.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        surveyListOut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        surveyListOut.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                surveyListOutValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(surveyListOut);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addASurvey, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modifyASurvey, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeASurvey, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeAllSurveys, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addASurvey)
                    .addComponent(removeASurvey)
                    .addComponent(modifyASurvey)
                    .addComponent(removeAllSurveys))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>
    
    private void initComponents(CSample sample) {

        AddASurvey = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        isFed = new javax.swing.JRadioButton("Federal",sample.isIsFederal());
        isState = new javax.swing.JRadioButton("State/Local",sample.isIsState());
        isPrivate = new javax.swing.JRadioButton("Private",sample.isIsPrivate());
        isSelf = new javax.swing.JRadioButton("Self-Employed",sample.isIsSelf());
        isUnemployed = new javax.swing.JRadioButton("Unemployed",sample.isIsUnemployed());
        jLabel9 = new javax.swing.JLabel();
        affectYes = new javax.swing.JRadioButton("Yes",sample.isImpYes());
        affectNo = new javax.swing.JRadioButton("No",sample.isImpNo());
        affectUnknown = new javax.swing.JRadioButton("Unknown",sample.isImpUnknown());
        jLabel10 = new javax.swing.JLabel();
        submitAddASurvey = new javax.swing.JButton();
        cancelAddASurvey = new javax.swing.JButton();
        zipCode = new javax.swing.JTextField(sample.getZip());
        blameR = new javax.swing.JCheckBox("Republicans(R)",sample.isBlameR());
        blameD = new javax.swing.JCheckBox("Democrats(D)",sample.isBlameD());
        blameO = new javax.swing.JCheckBox("Obamacare(O)",sample.isBlameO());
        blameC = new javax.swing.JCheckBox("The Debt Ceiling(C)",sample.isBlameC());
        participantNo = new javax.swing.JTextField(sample.getId());
        employmentType = new javax.swing.ButtonGroup();
        affectType = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addASurvey = new javax.swing.JButton();
        modifyASurvey = new javax.swing.JButton();
        removeASurvey = new javax.swing.JButton();
        removeAllSurveys = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        surveyListOut = new javax.swing.JList();

        AddASurvey.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        AddASurvey.setTitle("Add A Survey");
        AddASurvey.setMinimumSize(new java.awt.Dimension(552, 250));
        AddASurvey.setPreferredSize(new java.awt.Dimension(552, 250));

        jLabel6.setText("Participant No.");

        jLabel7.setText("Zip Code");

        jLabel8.setText("Employment Type");

        employmentType.add(isFed);

        employmentType.add(isState);

        employmentType.add(isPrivate);

        employmentType.add(isSelf);

        employmentType.add(isUnemployed);

        jLabel9.setText("Does the government shutown affect you?");

        affectType.add(affectYes);

        affectType.add(affectNo);

        affectType.add(affectUnknown);

        jLabel10.setText("Who/what is to blame for the government shutdown?");

        submitAddASurvey.setText("Submit");
        submitAddASurvey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitAddASurveyActionPerformed(evt);
            }
        });

        cancelAddASurvey.setText("Cancel");
        cancelAddASurvey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddASurveyActionPerformed(evt);
            }
        });

        participantNo.setEditable(false);

        javax.swing.GroupLayout AddASurveyLayout = new javax.swing.GroupLayout(AddASurvey.getContentPane());
        AddASurvey.getContentPane().setLayout(AddASurveyLayout);
        AddASurveyLayout.setHorizontalGroup(
            AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddASurveyLayout.createSequentialGroup()
                .addGroup(AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddASurveyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(AddASurveyLayout.createSequentialGroup()
                                .addComponent(isFed)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isState)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isPrivate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isSelf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(isUnemployed))
                            .addGroup(AddASurveyLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(participantNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(AddASurveyLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(zipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addGroup(AddASurveyLayout.createSequentialGroup()
                                .addComponent(affectYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(affectNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(affectUnknown))
                            .addComponent(jLabel10)))
                    .addGroup(AddASurveyLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(submitAddASurvey)
                        .addGap(133, 133, 133)
                        .addComponent(cancelAddASurvey))
                    .addGroup(AddASurveyLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(blameR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blameD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blameO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(blameC)))
                .addContainerGap())
        );
        AddASurveyLayout.setVerticalGroup(
            AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddASurveyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(participantNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(zipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(isFed)
                    .addComponent(isState)
                    .addComponent(isPrivate)
                    .addComponent(isSelf)
                    .addComponent(isUnemployed))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(affectYes)
                    .addComponent(affectNo)
                    .addComponent(affectUnknown))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blameR)
                    .addComponent(blameD)
                    .addComponent(blameO)
                    .addComponent(blameC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AddASurveyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitAddASurvey)
                    .addComponent(cancelAddASurvey)))
        );

        AddASurvey.getAccessibleContext().setAccessibleParent(null);
        pack();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Survey On The Government Shutdown");

        jLabel1.setText("Participant No.");

        jLabel2.setText("Zip Code");

        jLabel3.setText("Employment");

        jLabel4.setText("Impact");

        jLabel5.setText("Cause");

        addASurvey.setText("Add");
        addASurvey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CSampleAddASurveyClicked(evt);
            }
        });

        modifyASurvey.setText("Modify");
        modifyASurvey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyASurveyActionPerformed(evt);
            }
        });

        removeASurvey.setText("Remove");
        removeASurvey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeASurveyActionPerformed(evt);
            }
        });

        removeAllSurveys.setText("Remove All");
        removeAllSurveys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeAllSurveysActionPerformed(evt);
            }
        });

        surveyListOut.setModel(surveyList);
        surveyListOut.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        surveyListOut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        surveyListOut.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                surveyListOutValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(surveyListOut);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addASurvey, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modifyASurvey, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(removeASurvey, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(removeAllSurveys, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addASurvey)
                    .addComponent(removeASurvey)
                    .addComponent(modifyASurvey)
                    .addComponent(removeAllSurveys))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    //Handler Code
    private void CSampleAddASurveyClicked(java.awt.event.ActionEvent evt) {                                          
        isModifyInstance = false;
        participantNo.setText(keyGen.generateId());
        AddASurvey.setVisible(true);
    }                                         

    private void modifyASurveyActionPerformed(java.awt.event.ActionEvent evt) {                                              
        //System.out.println(selectedItem); 
        isModifyInstance = true;
        modSurvey = surveyObjects.get(selectedItem);
        participantNo.setText(modSurvey.getId());
        initComponents(modSurvey);
        AddASurvey.setVisible(true);
        //initComponents();
    }                                             

    private void submitAddASurveyActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        if (isModifyInstance == false){
            nuSurvey = new CSample(participantNo.getText(),zipCode.getText(),isFed.isSelected(),isState.isSelected(),isPrivate.isSelected(),isSelf.isSelected(),isUnemployed.isSelected(),
            affectYes.isSelected(),affectNo.isSelected(),affectUnknown.isSelected(),blameR.isSelected(),blameD.isSelected(),blameO.isSelected(),blameC.isSelected());
            surveyList.add(nuSurvey.getID()-1,nuSurvey.getString());
            //debugging
            //System.out.println(surveyListOut);
            //System.out.println(surveyListOut.getModel());
            surveyObjects.put(nuSurvey.getID()-1, nuSurvey);
            AddASurvey.dispose();
            //because Java's garbage collection logic is absolute fucking shit.  
            initComponents();
        } else {
            nuSurvey = new CSample(participantNo.getText(),zipCode.getText(),isFed.isSelected(),isState.isSelected(),isPrivate.isSelected(),isSelf.isSelected(),isUnemployed.isSelected(),
            affectYes.isSelected(),affectNo.isSelected(),affectUnknown.isSelected(),blameR.isSelected(),blameD.isSelected(),blameO.isSelected(),blameC.isSelected());
            surveyList.set(nuSurvey.getID()-1,nuSurvey.getString());
            surveyObjects.put(nuSurvey.getID()-1, nuSurvey);
            AddASurvey.dispose();
            initComponents();
        }
        
    }                                                

    private void cancelAddASurveyActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        AddASurvey.dispose();
        if(isModifyInstance == true){
            initComponents();
            isModifyInstance = false;
        } else {
            keyGen.decrementID();
            initComponents();
        }
    }                                                

    private void surveyListOutValueChanged(javax.swing.event.ListSelectionEvent evt) {                                           
        selectedItem = ((JList) evt.getSource()).getSelectedIndex();
        //System.out.println(surveyListOut.getModel());
        //System.out.println(selected);
    }                                          

    private void removeAllSurveysActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        surveyList.clear();
        surveyListOut.clearSelection();
        surveyListOut.repaint();
        initComponents();
    }                                                

    private void removeASurveyActionPerformed(java.awt.event.ActionEvent evt) {                                              
        surveyObjects.remove(selectedItem);
        surveyList.remove(selectedItem);
    }                                             

    //Utility Methods
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CSampler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CSampler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CSampler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CSampler.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CSampler().setVisible(true);
            }
        });
    }
    
    protected boolean isModifyInstance;
    protected CSample nuSurvey;
    protected CSample modSurvey;
    protected DefaultListModel surveyList;
    private final HashMap<Integer,CSample> surveyObjects;
    private int selectedItem;
    final idGenerator keyGen;
    // Variables declaration - do not modify                     
    private javax.swing.JDialog AddASurvey;
    private javax.swing.JButton addASurvey;
    private javax.swing.JRadioButton affectNo;
    private javax.swing.ButtonGroup affectType;
    private javax.swing.JRadioButton affectUnknown;
    private javax.swing.JRadioButton affectYes;
    private javax.swing.JCheckBox blameC;
    private javax.swing.JCheckBox blameD;
    private javax.swing.JCheckBox blameO;
    private javax.swing.JCheckBox blameR;
    private javax.swing.JButton cancelAddASurvey;
    private javax.swing.ButtonGroup employmentType;
    private javax.swing.JRadioButton isFed;
    private javax.swing.JRadioButton isPrivate;
    private javax.swing.JRadioButton isSelf;
    private javax.swing.JRadioButton isState;
    private javax.swing.JRadioButton isUnemployed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modifyASurvey;
    private javax.swing.JTextField participantNo;
    private javax.swing.JButton removeASurvey;
    private javax.swing.JButton removeAllSurveys;
    private javax.swing.JButton submitAddASurvey;
    private javax.swing.JList surveyListOut;
    private javax.swing.JTextField zipCode;
    // End of variables declaration                   
}
